# Generated by Django 5.0.2 on 2024-03-18 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 18, 13, 52, 47, 450167, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
